---
name: Release to Github Pages
on:
  push:
    branches: [ dev ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy To GHPages
      uses: manzoorwanijk/action-deploy-to-repo@master
      with:
        src_dir: /
        target_owner: 2dos
        target_repo: DK64-Randomizer-Dev
        target_dir: /
        target_branch: main
        access_token: ${{ secrets.ACCESS_TOKEN }}
        precommit_command: "echo 'This repo Dev Github Pages for DK64Rando, you need to go to https://github.com/2dos/DK64-Randomizer' > README.md && echo 'dev.dk64randomizer.com' > CNAME && touch .nojekyll"